#!/bin/bash
UUID_FILE="/boot/flyitalyadsb-uuid"
if ! [[ -f "$UUID_FILE" ]]; then
    UUID_FILE="/usr/local/share/flyitalyadsb/flyitalyadsb-uuid"
fi
source /etc/default/flyitalyadsb
SED=$(echo "$a" |sed -e 's$^$https://statistiche.flyitalyadsb.com/login?uuid=$' "$UUID_FILE")
echo $SED"&user="$UTENTE
